FROM ghcr.io/mrdvd/xetex-base:labs

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 \
    python3-pip \
    unzip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# install python dependencies
COPY requirements.txt /tmp/requirements.txt
RUN pip3 install --no-cache-dir -r /tmp/requirements.txt

# install yq
ENV VERSION=v4.2.0
ENV PLATFORM=linux_amd64

RUN curl -sL https://github.com/mikefarah/yq/releases/download/${VERSION}/yq_${PLATFORM}.tar.gz | \
    tar -xzf - -C /usr/local/bin ./yq_${PLATFORM} && \
    mv /usr/local/bin/yq_${PLATFORM} /usr/local/bin/yq

# download dataset
RUN mkdir -p /lab && \
    curl -L https://archive.ics.uci.edu/static/public/320/student+performance.zip -o /lab/dataset.zip && \
    unzip /lab/dataset.zip -d /lab && \
    unzip /lab/student.zip -d /lab && \
    rm /lab/dataset.zip && \
    rm /lab/student.zip && \
    rm /lab/.student.zip_old